import type { Metadata } from "next";

import { Montserrat } from "next/font/google";

import "./globals.css";
import Sidebar from "@/components/Sidebar";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
     <body className="font-sans antialiased h-full">


<Sidebar />
  <main className="ml-60 flex-1">{children}</main>
      </body>
    </html>
  );
}
