// src/app/api/plannings/[planningId]/route.ts
import { MongoClient, ObjectId } from "mongodb";
import crypto from "crypto";
import { getCorsHeaders } from "@/lib/cors";

export const runtime = "nodejs";

/* ----------------------------- Session helpers ---------------------------- */

function sign(payload: string, secret: string) {
  return crypto.createHmac("sha256", secret).update(payload).digest("hex");
}

function getCookie(req: Request, name: string) {
  const cookie = req.headers.get("cookie") || "";
  const parts = cookie.split(";").map((p) => p.trim());
  const found = parts.find((p) => p.startsWith(name + "="));
  return found ? decodeURIComponent(found.split("=").slice(1).join("=")) : null;
}

function readSession(req: Request, secret: string) {
  const token = getCookie(req, "session");
  if (!token) return null;

  const [payload, sig] = token.split(".");
  if (!payload || !sig) return null;
  if (sign(payload, secret) !== sig) return null;

  try {
    return JSON.parse(Buffer.from(payload, "base64url").toString("utf8"));
  } catch {
    return null;
  }
}

/* -------------------------------- Helpers -------------------------------- */

function safeString(v: any) {
  return typeof v === "string" ? v.trim() : "";
}

function toObjectIdOrNull(v: any) {
  try {
    if (!v) return null;
    return new ObjectId(String(v));
  } catch {
    return null;
  }
}

function firstNonEmpty(...values: any[]) {
  for (const v of values) {
    const s = safeString(v);
    if (s) return s;
  }
  return "";
}

const AUTO_DEMOLITION_ITEM_ID = "auto-demolition-ist";

function safeBoolean(v: any, fallback = false) {
  return typeof v === "boolean" ? v : fallback;
}

function syncDemolitionItem(existingItems: any[], ist: any) {
  const demolitionNeeded = safeBoolean(ist?.demolitionNeeded);

  const withoutAutoDemolition = existingItems.filter((item) => {
    return (
      safeString(item?.id) !== AUTO_DEMOLITION_ITEM_ID &&
      safeString(item?.source) !== "auto-ist-demolition"
    );
  });

  if (!demolitionNeeded) {
    return withoutAutoDemolition;
  }

  const existingAutoItem = existingItems.find((item) => {
    return (
      safeString(item?.id) === AUTO_DEMOLITION_ITEM_ID ||
      safeString(item?.source) === "auto-ist-demolition"
    );
  });

  const quantity =
    typeof existingAutoItem?.quantity === "number"
      ? existingAutoItem.quantity
      : 1;

  const unitPriceNet =
    typeof existingAutoItem?.unitPriceNet === "number"
      ? existingAutoItem.unitPriceNet
      : 0;

  const notes = firstNonEmpty(
    ist?.demolitionNotes,
    ist?.demolitionDetails,
    ist?.notes
  );

  const demolitionItem = {
    ...existingAutoItem,

    id: AUTO_DEMOLITION_ITEM_ID,
    category: "Demontage",
    brand: "",
    model: "",
    name: "Demontage / Rückbau bestehende Anlage",

    quantity,
    unit: "Pauschal",
    unitLabel: "Pauschal",

    unitPriceNet,
    lineTotalNet: Number((quantity * unitPriceNet).toFixed(2)),

    source: "auto-ist-demolition",
    autoGenerated: true,
    notes,
  };

  return [...withoutAutoDemolition, demolitionItem];
}

function buildCustomerNameFromProfile(profile: any) {
  const businessName = firstNonEmpty(
    profile?.businessName,
    profile?.companyName,
    profile?.company
  );
  if (businessName) return businessName;

  const fullName = [
    safeString(profile?.contactFirstName),
    safeString(profile?.contactLastName),
  ]
    .filter(Boolean)
    .join(" ")
    .trim();

  return fullName || safeString(profile?.name) || "";
}

function extractCityFromAddress(address: any) {
  const a = safeString(address);
  if (!a) return "";

  const parts = a.split(",");
  const lastPart = parts[parts.length - 1]?.trim() || "";

  const match = lastPart.match(/^(\d{4})\s+(.+)$/);
  if (match) return match[2].trim();

  return lastPart;
}

function deriveProjectTitleFromData(profile: any, ist: any) {
  const businessName = firstNonEmpty(
    profile?.businessName,
    profile?.companyName,
    profile?.company
  );

  const privateName = firstNonEmpty(
    [safeString(profile?.contactFirstName), safeString(profile?.contactLastName)]
      .filter(Boolean)
      .join(" "),
    profile?.name
  );

  const displayName = businessName || privateName;

  const city = firstNonEmpty(
    profile?.city,
    profile?.place,
    profile?.location,
    profile?.postalCity,
    profile?.addressCity,
    ist?.city,
    ist?.place,
    ist?.location,
    extractCityFromAddress(profile?.address),
    extractCityFromAddress(ist?.address)
  );

  if (displayName && city) return `PV ${displayName} - ${city}`;
  if (displayName) return `PV ${displayName}`;
  return "";
}

function shouldAutoRenameTitle(existingTitle: string) {
  const t = safeString(existingTitle).toLowerCase();
  return !t || t === "neues projekt" || t === "unbenanntes projekt";
}

function deriveSummaryFromPlanner(docLike: any) {
  const data = docLike?.data ?? {};
  const existingSummary = docLike?.summary ?? {};

  const planner = data?.planner ?? {};

  const panels = Array.isArray(planner?.panels)
    ? planner.panels
    : Array.isArray(data?.panels)
      ? data.panels
      : [];

  const layers = Array.isArray(planner?.layers)
    ? planner.layers
    : Array.isArray(data?.layers)
      ? data.layers
      : [];

  const catalogPanels = Array.isArray(planner?.catalogPanels)
    ? planner.catalogPanels
    : Array.isArray(data?.catalogPanels)
      ? data.catalogPanels
      : [];

  const selectedPanelId =
    safeString(existingSummary.selectedPanelId) ||
    safeString(planner?.selectedPanelId) ||
    safeString(data?.selectedPanelId);

  const selectedPanel = catalogPanels.find(
    (p: any) => safeString(p?.id) === selectedPanelId
  );

  const moduleCount = panels.length;

  const panelWp =
    typeof selectedPanel?.wp === "number"
      ? selectedPanel.wp
      : 0;

  const dcPowerKw =
    moduleCount > 0 && panelWp > 0
      ? Number(((moduleCount * panelWp) / 1000).toFixed(2))
      : typeof existingSummary.dcPowerKw === "number"
        ? existingSummary.dcPowerKw
        : 0;

  return {
    customerName:
      safeString(existingSummary.customerName) ||
      buildCustomerNameFromProfile(data?.profile),

    moduleCount,
    selectedPanelId,
    dcPowerKw,
    roofCount: layers.length,

    hasSnapshot:
      typeof planner?.snapshot === "object"
        ? true
        : typeof existingSummary.hasSnapshot === "boolean"
          ? existingSummary.hasSnapshot
          : false,

    lastCalculatedAt: new Date().toISOString(),
  };
}

function jsonResponse(origin: string | null, body: any, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      "Content-Type": "application/json",
      ...getCorsHeaders(origin),
    },
  });
}

/* -------------------------------- OPTIONS -------------------------------- */

export async function OPTIONS(req: Request) {
  const origin = req.headers.get("origin");
  return new Response(null, {
    status: 204,
    headers: getCorsHeaders(origin),
  });
}

/* --------------------------------- PATCH --------------------------------- */

export async function PATCH(
  req: Request,
  { params }: { params: Promise<{ planningId: string }> },
) {
  const origin = req.headers.get("origin");
  const { planningId } = await params;

  const uri = process.env.MONGODB_URI;
  const secret = process.env.SESSION_SECRET;

  if (!uri) {
    return jsonResponse(origin, { ok: false, error: "Missing MONGODB_URI" }, 500);
  }

  if (!secret) {
    return jsonResponse(origin, { ok: false, error: "Missing SESSION_SECRET" }, 500);
  }

  const session = readSession(req, secret);
  if (!session) {
    return jsonResponse(origin, { ok: false, error: "Not logged in" }, 401);
  }

  if (!planningId) {
    return jsonResponse(
      origin,
      { ok: false, error: "Route params missing. Check folder name is [planningId]." },
      500
    );
  }

  const planningObjectId = toObjectIdOrNull(planningId);
  if (!planningObjectId) {
    return jsonResponse(origin, { ok: false, error: "Invalid planningId" }, 400);
  }

  const body = await req.json().catch(() => ({} as any));

  const profile = body?.profile;
  const ist = body?.ist;
  const planner = body?.planner;

  const title = body?.title;
  const customerId = body?.customerId;
  const planningNumber = body?.planningNumber;
  const commercial = body?.commercial;
  const summary = body?.summary;
  const parts = body?.parts;

  // NEW: support Bericht / reportOptions payload
  const reportOptions =
    body?.reportOptions ??
    body?.data?.reportOptions ??
    body?.["data.reportOptions"];

  const hasPlannerPayload =
    (profile && typeof profile === "object") ||
    (ist && typeof ist === "object") ||
    (planner && typeof planner === "object") ||
    (parts && typeof parts === "object") ||
    (reportOptions && typeof reportOptions === "object");

  const hasCrmPayload =
    typeof title === "string" ||
    typeof customerId === "string" ||
    typeof planningNumber === "string" ||
    (commercial && typeof commercial === "object") ||
    (summary && typeof summary === "object");

  if (!hasPlannerPayload && !hasCrmPayload) {
    return jsonResponse(
      origin,
      {
        ok: false,
        error:
          "Send planner data ({ profile }, { ist }, { planner }, { parts }, { reportOptions }) or CRM fields ({ title, customerId, planningNumber, commercial, summary })",
      },
      400
    );
  }

  const setObj: Record<string, any> = { updatedAt: new Date() };

  const client = new MongoClient(uri, { serverSelectionTimeoutMS: 5000 });

  try {
    await client.connect();
    const db = client.db();
    const plannings = db.collection("plannings");
    const customers = db.collection("customers");

    const existingPlanning = await plannings.findOne({
      _id: planningObjectId,
      companyId: session.activeCompanyId,
    });

    if (!existingPlanning) {
      return jsonResponse(origin, { ok: false, error: "Planning not found" }, 404);
    }

    const canAutoRename = shouldAutoRenameTitle(
      safeString((existingPlanning as any)?.title)
    );

    // -------------------- CRM-friendly metadata --------------------

    if (typeof title === "string") {
      setObj.title = safeString(title) || "Unbenanntes Projekt";
    }

    if (typeof customerId === "string") {
      setObj.customerId = safeString(customerId) || null;
    }

    if (typeof planningNumber === "string") {
      setObj.planningNumber = safeString(planningNumber);
    }

    if (commercial && typeof commercial === "object") {
      if (typeof commercial.stage === "string") {
        setObj["commercial.stage"] = safeString(commercial.stage) || "lead";
      }
      if (typeof commercial.valueChf === "number") {
        setObj["commercial.valueChf"] = commercial.valueChf;
      }
      if (typeof commercial.assignedToUserId === "string") {
        setObj["commercial.assignedToUserId"] =
          safeString(commercial.assignedToUserId) || null;
      }
      if (typeof commercial.source === "string") {
        setObj["commercial.source"] = safeString(commercial.source);
      }
      if (typeof commercial.label === "string") {
        setObj["commercial.label"] = safeString(commercial.label);
      }
    }

    if (summary && typeof summary === "object") {
      if (typeof summary.customerName === "string") {
        setObj["summary.customerName"] = safeString(summary.customerName);
      }
      if (typeof summary.moduleCount === "number") {
        setObj["summary.moduleCount"] = summary.moduleCount;
      }
      if (typeof summary.selectedPanelId === "string") {
        setObj["summary.selectedPanelId"] = safeString(summary.selectedPanelId);
      }
      if (typeof summary.dcPowerKw === "number") {
        setObj["summary.dcPowerKw"] = summary.dcPowerKw;
      }
      if (typeof summary.roofCount === "number") {
        setObj["summary.roofCount"] = summary.roofCount;
      }
      if (typeof summary.hasSnapshot === "boolean") {
        setObj["summary.hasSnapshot"] = summary.hasSnapshot;
      }
      if ("lastCalculatedAt" in summary) {
        setObj["summary.lastCalculatedAt"] = summary.lastCalculatedAt ?? null;
      }
    }

    // -------------------- Planner flow payload --------------------

    if (profile && typeof profile === "object") {
      setObj["data.profile"] = profile;
      setObj.currentStep = "ist";

      const customerName = buildCustomerNameFromProfile(profile);
      if (customerName) {
        setObj["summary.customerName"] = customerName;
      }

      const autoTitle = deriveProjectTitleFromData(profile, ist);
      if (autoTitle && canAutoRename) {
        setObj.title = autoTitle;
      }
    }

if (ist && typeof ist === "object") {
  const existingIst = (existingPlanning as any)?.data?.ist ?? {};

  const mergedIst = {
    ...existingIst,
    ...ist,
    checklist:
      ist?.checklist && typeof ist.checklist === "object"
        ? {
            ...(existingIst?.checklist ?? {}),
            ...ist.checklist,
          }
        : existingIst?.checklist,
  };

  setObj["data.ist"] = mergedIst;
  setObj.currentStep = safeString(body?.currentStep) || "building";

  const existingParts = (existingPlanning as any)?.data?.parts ?? {};
  const existingItems = Array.isArray(existingParts?.items)
    ? existingParts.items
    : [];

  setObj["data.parts"] = {
    ...existingParts,
    items: syncDemolitionItem(existingItems, mergedIst),
  };

  const effectiveProfile =
    profile && typeof profile === "object"
      ? profile
      : (existingPlanning as any)?.data?.profile;

  const autoTitle = deriveProjectTitleFromData(effectiveProfile, mergedIst);
  if (autoTitle && canAutoRename) {
    setObj.title = autoTitle;
  }
}

    if (planner && typeof planner === "object") {
      const existingPlannerState = (existingPlanning as any)?.data?.planner ?? {};

      const mergedPlanner = {
        ...existingPlannerState,
        ...planner,
        snapshot: {
          ...(existingPlannerState?.snapshot ?? {}),
          ...(planner?.snapshot ?? {}),
        },
      };

      if (!mergedPlanner.snapshot?.url && existingPlannerState?.snapshot) {
        mergedPlanner.snapshot = {
          ...existingPlannerState.snapshot,
          ...(planner?.snapshot ?? {}),
        };
      }

      setObj["data.planner"] = mergedPlanner;

      const computedSummary = deriveSummaryFromPlanner({
        ...(existingPlanning as any),
        data: {
          ...((existingPlanning as any)?.data ?? {}),
          planner: mergedPlanner,
        },
        summary: (existingPlanning as any)?.summary ?? {},
      });

      setObj["summary.moduleCount"] = computedSummary.moduleCount;
      setObj["summary.selectedPanelId"] = computedSummary.selectedPanelId;
      setObj["summary.dcPowerKw"] = computedSummary.dcPowerKw;
      setObj["summary.roofCount"] = computedSummary.roofCount;
      setObj["summary.hasSnapshot"] = computedSummary.hasSnapshot;
      setObj["summary.lastCalculatedAt"] = computedSummary.lastCalculatedAt;

      const plannerStep = safeString(planner?.step || mergedPlanner?.step);

      if (plannerStep === "modules") {
        setObj.currentStep = "modules";
      } else if (plannerStep === "building") {
        setObj.currentStep = "building";
      } else {
        setObj.currentStep =
          safeString((existingPlanning as any)?.currentStep) || "building";
      }
    }

    if (parts && typeof parts === "object") {
      const existingParts = (existingPlanning as any)?.data?.parts ?? {};

      const normalizedItems = Array.isArray(parts?.items)
        ? parts.items
        : existingParts.items ?? [];

      const normalizedFormDocuments =
        parts?.formDocuments && typeof parts.formDocuments === "object"
          ? parts.formDocuments
          : existingParts.formDocuments ?? {};

      setObj["data.parts"] = {
        ...existingParts,
        ...parts,
        items: normalizedItems,
        formDocuments: normalizedFormDocuments,
      };

      setObj.currentStep = "parts";
    }

    // NEW: save Bericht options
    if (reportOptions && typeof reportOptions === "object") {
      const existingReportOptions =
        (existingPlanning as any)?.data?.reportOptions ?? {};

      setObj["data.reportOptions"] = {
        ...existingReportOptions,
        ...reportOptions,
      };

      // se siamo in Bericht, non sovrascrivere currentStep con qualcosa di sbagliato
      if (!setObj.currentStep) {
        setObj.currentStep = "bericht";
      }
    }

    // -------------------- customerId validation / sync --------------------

    if (typeof customerId === "string" && safeString(customerId)) {
      const customerObjectId = toObjectIdOrNull(customerId);

      if (!customerObjectId) {
        return jsonResponse(origin, { ok: false, error: "Invalid customerId" }, 400);
      }

      const customer = await customers.findOne({
        _id: customerObjectId,
        companyId: session.activeCompanyId,
      });

      if (!customer) {
        return jsonResponse(
          origin,
          { ok: false, error: "Customer not found in active company" },
          400
        );
      }

      const customerName =
        safeString((customer as any).name) ||
        safeString((customer as any).companyName) ||
        [safeString((customer as any).firstName), safeString((customer as any).lastName)]
          .filter(Boolean)
          .join(" ")
          .trim();

      if (customerName && !setObj["summary.customerName"]) {
        setObj["summary.customerName"] = customerName;
      }
    }

    const res = await plannings.updateOne(
      { _id: planningObjectId, companyId: session.activeCompanyId },
      { $set: setObj },
    );

    if (res.matchedCount === 0) {
      return jsonResponse(origin, { ok: false, error: "Planning not found" }, 404);
    }

    const updated = await plannings.findOne({
      _id: planningObjectId,
      companyId: session.activeCompanyId,
    });

    if (!updated) {
      return jsonResponse(origin, { ok: false, error: "Planning not found after update" }, 404);
    }

    const normalized = {
      ...updated,
      _id: String((updated as any)._id),
      summary: deriveSummaryFromPlanner(updated),
      title: safeString((updated as any)?.title) || "Unbenanntes Projekt",
      planningNumber: safeString((updated as any)?.planningNumber) || "",
      commercial: {
        stage: safeString((updated as any)?.commercial?.stage) || "lead",
        valueChf:
          typeof (updated as any)?.commercial?.valueChf === "number"
            ? (updated as any).commercial.valueChf
            : 0,
        assignedToUserId: (updated as any)?.commercial?.assignedToUserId ?? null,
        source: safeString((updated as any)?.commercial?.source),
        label: safeString((updated as any)?.commercial?.label),
      },
      customerId: (updated as any)?.customerId ?? null,
    };

    return jsonResponse(origin, { ok: true, planning: normalized }, 200);
  } catch (e: any) {
    console.error("UPDATE PLANNING ERROR:", e);
    return jsonResponse(
      origin,
      { ok: false, error: e?.message ?? "Unknown error" },
      500
    );
  } finally {
    await client.close().catch(() => {});
  }
}

/* ---------------------------------- GET ---------------------------------- */

export async function GET(
  req: Request,
  { params }: { params: Promise<{ planningId: string }> },
) {
  const origin = req.headers.get("origin");
  const { planningId } = await params;

  const uri = process.env.MONGODB_URI;
  const secret = process.env.SESSION_SECRET;

  if (!uri) {
    return jsonResponse(origin, { ok: false, error: "Missing MONGODB_URI" }, 500);
  }

  if (!secret) {
    return jsonResponse(origin, { ok: false, error: "Missing SESSION_SECRET" }, 500);
  }

  const session = readSession(req, secret);
  if (!session) {
    return jsonResponse(origin, { ok: false, error: "Not logged in" }, 401);
  }

  if (!planningId) {
    return jsonResponse(
      origin,
      { ok: false, error: "Route params missing. Check folder name is [planningId]." },
      500
    );
  }

  const planningObjectId = toObjectIdOrNull(planningId);
  if (!planningObjectId) {
    return jsonResponse(origin, { ok: false, error: "Invalid planningId" }, 400);
  }

  const client = new MongoClient(uri, { serverSelectionTimeoutMS: 5000 });

  try {
    await client.connect();
    const db = client.db();
    const plannings = db.collection("plannings");

    const doc = await plannings.findOne({
      _id: planningObjectId,
      companyId: session.activeCompanyId,
    });

    if (!doc) {
      return jsonResponse(origin, { ok: false, error: "Planning not found" }, 404);
    }

    const normalized = {
      ...doc,
      _id: String((doc as any)._id),
      summary: deriveSummaryFromPlanner(doc),
      title: safeString((doc as any)?.title) || "Unbenanntes Projekt",
      planningNumber: safeString((doc as any)?.planningNumber) || "",
      commercial: {
        stage: safeString((doc as any)?.commercial?.stage) || "lead",
        valueChf:
          typeof (doc as any)?.commercial?.valueChf === "number"
            ? (doc as any).commercial.valueChf
            : 0,
        assignedToUserId: (doc as any)?.commercial?.assignedToUserId ?? null,
        source: safeString((doc as any)?.commercial?.source),
        label: safeString((doc as any)?.commercial?.label),
      },
      customerId: (doc as any)?.customerId ?? null,
    };

    return jsonResponse(origin, { ok: true, planning: normalized }, 200);
  } catch (e: any) {
    console.error("GET PLANNING ERROR:", e);
    return jsonResponse(
      origin,
      { ok: false, error: e?.message ?? "Unknown error" },
      500
    );
  } finally {
    await client.close().catch(() => {});
  }
}

export async function DELETE(
  req: Request,
  { params }: { params: Promise<{ planningId: string }> },
) {
  const origin = req.headers.get("origin");
  const { planningId } = await params;

  const uri = process.env.MONGODB_URI;
  const secret = process.env.SESSION_SECRET;

  if (!uri) {
    return jsonResponse(origin, { ok: false, error: "Missing MONGODB_URI" }, 500);
  }

  if (!secret) {
    return jsonResponse(origin, { ok: false, error: "Missing SESSION_SECRET" }, 500);
  }

  const session = readSession(req, secret);
  if (!session?.activeCompanyId) {
    return jsonResponse(origin, { ok: false, error: "Not logged in" }, 401);
  }

  const planningObjectId = toObjectIdOrNull(planningId);
  if (!planningObjectId) {
    return jsonResponse(origin, { ok: false, error: "Invalid planningId" }, 400);
  }

  const client = new MongoClient(uri, { serverSelectionTimeoutMS: 5000 });

  try {
    await client.connect();
    const db = client.db();
    const plannings = db.collection("plannings");

    const res = await plannings.deleteOne({
      _id: planningObjectId,
      companyId: session.activeCompanyId,
    });

    if (res.deletedCount === 0) {
      return jsonResponse(origin, { ok: false, error: "Planning not found" }, 404);
    }

    return jsonResponse(origin, { ok: true }, 200);
  } catch (e: any) {
    console.error("DELETE PLANNING ERROR:", e);
    return jsonResponse(
      origin,
      { ok: false, error: e?.message ?? "Unknown error" },
      500
    );
  } finally {
    await client.close().catch(() => {});
  }
}